title: Droonga
markdown: kramdown
droonga_version: 0.7.0
copyright_year: 2013
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description: Droonga is a scalable data processing engine.

kramdown:
  enable_coderay: true
