title: Droonga
markdown: kramdown
permalink: /news/:year/:month/:day/:title.html
url: http://droonga.org
blog_base_url: /news/
droonga_version: 1.0.2
copyright_year: 2013-2014
exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "README.md"]
description: Droonga is a scalable data processing engine.

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
